version: "3.8"
services:
  jupyter:
    image: jupyter/base-notebook:latest
    build:
      context: .
      dockerfile: DockerfileJupyterNotebook
    volumes:
      - ./airbnb-scraping:/home/jovyan/airbnb-scraping
      - ./database-operations:/home/jovyan/database-operations
      - ./eda:/home/jovyan/eda
      - ./nlp:/home/jovyan/nlp
      - ./rental-prices:/home/jovyan/rental-prices
      - ./data:/home/jovyan/data
    ports:
      - "8888:8888"
  postgres:
    image: postgres:latest
    container_name: adsproject_postgres
    build:
      context: .
      dockerfile: DockerfilePostgres
    environment:
      POSTGRES_DB: adsproject
      POSTGRES_USER: ads
      POSTGRES_PASSWORD: admin123!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - my-network

  python:
    build: .
    container_name: dbops
    depends_on:
      - postgres
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "database-operations/docker/dbops.py"]
    networks:
      - my-network

volumes:
  postgres_data:

## Before running docker compose, create the network in bash with 'docker network create my-network'
networks:
  my-network:
    external: true
